### ISSUE TITLE
LX catalogue

### ISSUE THREAD

**Issue by wjdp** [newtheatre/website#11]
Gels site http://gels.newtheatre.org.uk could be rebuilt as a **very minimal** jekyll site in a separate repo built and run completely with GitHub pages (i.e. no travis, no staircase server)

Single file `_data/gels.yml` would look like:

```
- gel:
  code: L201
  color: #C3E1FB
  stock:
    - sheet: 3
    - cut: 17

&c
```

Site would be built, either a pure HTML output or same with JavaScript fun added in.

Could be extended for gobos.

**Comment by wjdp** [comment]
I've much work to do today, it's going to be very hard not to do this instead

**Comment by nhyty** [comment]
Will, work, however I agree about this.

**Comment by wjdp** [comment]
Had a think: designers need to know about what colour we have, they need to know other things too:

- What fixtures
- What colours
- What gobos

Cables and other small accessories I don't think warrant trying to catalogue.

### Lighting Fixture

```
- fixture:
  brand: Selecon 
  model: Rama
  type: Fresnel
  stock:
    - good: 10
    - repair: 2
    - broken: 0
```

Conditions: good is good, repair is working but could do with work/not fully functional, broken is out of service
